CONFIGS_DIR = "./configs/"
ACCESSDEVICES = "inventory/accessInventory.csv"
COREDEVICES = "inventory/coreInventory.csv"
ACCESSTEMPLATE = "./templates/3850-access-v1.txt"
CORETEMPLATE = "./templates/6840-core-vss-v1.txt"